name: Hourly AQI Data Fetch

on:
  schedule:
    - cron: '19 * * * *' # Runs at minute 0 past every hour
  workflow_dispatch: # Allows you to manually trigger it from GitHub

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Feature Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
        run: python FeaturePipeline.py